class Question {
  final String question;
  final List<String> options;
  final int correctIndex;

  Question({
    required this.question,
    required this.options,
    required this.correctIndex,
  });
}

final Map<String, List<Question>> questionBank = {
  '상식': [
Question(question: '세계에서 가장 많은 언어가 사용되는 나라는?', options: ['중국', '인도', '파푸아뉴기니', '나이지리아'], correctIndex: 2),
Question(question: '빛의 속도는 진공에서 약 얼마인가요?', options: ['30만 km/s', '10만 km/s', '15만 km/s', '5만 km/s'], correctIndex: 0),
Question(question: '다음 중 비행기를 최초로 발명한 인물은?', options: ['에디슨', '오토 릴리엔탈', '라이트 형제', '레오나르도 다빈치'], correctIndex: 2),
Question(question: '인간의 몸에서 가장 무거운 기관은?', options: ['심장', '뇌', '간', '폐'], correctIndex: 2),
Question(question: '세계에서 가장 면적이 큰 국가는?', options: ['중국', '캐나다', '러시아', '미국'], correctIndex: 2),
Question(question: '해양 면적이 가장 넓은 대양은?', options: ['대서양', '북극해', '남극해', '태평양'], correctIndex: 3),
Question(question: '유럽연합(EU)의 본부는 어디에 있을까요?', options: ['파리', '베를린', '브뤼셀', '암스테르담'], correctIndex: 2),
Question(question: '1년 중 낮이 가장 긴 날은?', options: ['춘분', '하지', '추분', '동지'], correctIndex: 1),
Question(question: '광합성의 주된 장소는?', options: ['잎', '줄기', '뿌리', '꽃'], correctIndex: 0),
Question(question: '화학식 CH4는 무엇을 나타내나요?', options: ['에탄', '메탄', '프로판', '부탄'], correctIndex: 1),
Question(question: '세계 3대 폭포 중 하나로, 아프리카에 위치한 폭포는?', options: ['나이아가라', '빅토리아', '이구아수', '보스톤'], correctIndex: 1),
Question(question: '사람의 평균 체온은?', options: ['36.5도', '37도', '38도', '35도'], correctIndex: 0),
Question(question: '기상 현상 중 \'엘니뇨\'는 어떤 변화와 관련이 있나요?', options: ['태풍', '지진', '해수 온도', '오존층'], correctIndex: 2),
Question(question: '비타민 C가 가장 풍부한 과일은?', options: ['바나나', '레몬', '사과', '포도'], correctIndex: 1),
Question(question: '국제 올림픽 위원회(IOC)가 있는 도시는?', options: ['로잔', '제네바', '파리', '베를린'], correctIndex: 0),
Question(question: '지구 대기의 대부분은 어떤 기체인가요?', options: ['산소', '이산화탄소', '질소', '수소'], correctIndex: 2),
Question(question: '물의 끓는점은 해발고도에 따라 어떻게 변하나요?', options: ['높아진다', '낮아진다', '변하지 않는다', '처음에만 변함'], correctIndex: 1),
Question(question: '지구에서 가장 깊은 해구는?', options: ['마리아나 해구', '통가 해구', '쿠릴 해구', '일본 해구'], correctIndex: 0),
Question(question: '전파보다 파장이 짧은 전자기파는?', options: ['마이크로파', '자외선', '가시광선', '적외선'], correctIndex: 1),
Question(question: '세계 4대 문명 중 유일하게 문자를 남긴 문명은?', options: ['이집트 문명', '메소포타미아 문명', '황하 문명', '인더스 문명'], correctIndex: 1),
],
  '연산': [
Question(question: '7 × (3 + 2) = ?', options: ['35', '21', '30', '40'], correctIndex: 0),
Question(question: '24 ÷ 3 × 2 = ?', options: ['16', '12', '8', '10'], correctIndex: 1),
Question(question: '10 + 3 × 2 = ?', options: ['26', '20', '16', '30'], correctIndex: 2),
Question(question: '100 - (4 × 5) = ?', options: ['60', '80', '70', '90'], correctIndex: 1),
Question(question: '72 ÷ 8 = ?', options: ['6', '8', '9', '7'], correctIndex: 2),
Question(question: '0.5 + 0.75 = ?', options: ['1.5', '1.25', '1.0', '1.75'], correctIndex: 1),
Question(question: '12의 약수가 아닌 것은?', options: ['2', '4', '6', '7'], correctIndex: 3),
Question(question: '소수는 무엇인가요?', options: ['1과 자기 자신만을 약수로 가지는 수', '짝수', '홀수', '나누어지는 수'], correctIndex: 0),
Question(question: '3의 배수인 것은?', options: ['14', '15', '17', '19'], correctIndex: 1),
Question(question: '가장 작은 세 자리 수는?', options: ['99', '100', '101', '102'], correctIndex: 1),
Question(question: '3.14는 무엇을 나타내나요?', options: ['원주율', '평균', '분수', '속도'], correctIndex: 0),
Question(question: '1/2 + 1/4 = ?', options: ['1/4', '1/2', '3/4', '1'], correctIndex: 2),
Question(question: '소수점 둘째 자리까지 반올림한 3.456은?', options: ['3.4', '3.45', '3.46', '3.5'], correctIndex: 2),
Question(question: '가장 큰 네 자리 수는?', options: ['9999', '999', '10000', '9990'], correctIndex: 0),
Question(question: '12%는 소수로?', options: ['0.12', '1.2', '0.012', '12'], correctIndex: 0),
Question(question: '5의 제곱은?', options: ['10', '20', '25', '15'], correctIndex: 2),
Question(question: '루트 16의 값은?', options: ['3', '4', '5', '6'], correctIndex: 1),
Question(question: '1km는 몇 m인가요?', options: ['1000', '100', '10', '10000'], correctIndex: 0),
Question(question: '세 변이 모두 같은 삼각형은?', options: ['정삼각형', '이등변삼각형', '직각삼각형', '둔각삼각형'], correctIndex: 0),
Question(question: '8.6 - 2.3 = ?', options: ['6.3', '5.3', '7.3', '4.3'], correctIndex: 0),
],
  '코딩': [
Question(question: 'Python에서 "=="의 의미는?', options: ['할당', '비교', '곱셈', '나눗셈'], correctIndex: 1),
Question(question: 'Java에서 클래스를 정의할 때 사용하는 키워드는?', options: ['function', 'define', 'class', 'method'], correctIndex: 2),
Question(question: '웹 페이지의 디자인을 담당하는 언어는?', options: ['HTML', 'CSS', 'JavaScript', 'SQL'], correctIndex: 1),
Question(question: 'Python에서 리스트의 첫 요소를 가져오는 방법은?', options: ['list.0', 'list[0]', 'list{0}', 'list(0)'], correctIndex: 1),
Question(question: '조건문에 사용되는 키워드는?', options: ['for', 'if', 'while', 'print'], correctIndex: 1),
Question(question: 'JavaScript에서 문자열을 연결할 때 사용하는 연산자는?', options: ['+', '-', '*', '/'], correctIndex: 0),
Question(question: 'C언어에서 "int"는 어떤 자료형을 의미하나요?', options: ['문자열', '실수', '정수', '참/거짓'], correctIndex: 2),
Question(question: '파이썬에서 반복문 중 하나는?', options: ['repeat', 'do', 'for', 'check'], correctIndex: 2),
Question(question: 'HTML에서 문단을 나타내는 태그는?', options: ['<p>', '<h1>', '<br>', '<div>'], correctIndex: 0),
Question(question: '자바스크립트에서 변수를 선언하는 키워드가 아닌 것은?', options: ['let', 'var', 'const', 'def'], correctIndex: 3),
Question(question: 'Python에서 "len()" 함수는?', options: ['출력', '길이 반환', '곱셈', '정렬'], correctIndex: 1),
Question(question: 'SQL에서 데이터를 조회하는 명령은?', options: ['SELECT', 'INSERT', 'DELETE', 'UPDATE'], correctIndex: 0),
Question(question: '코딩에서 주석의 역할은?', options: ['출력', '컴파일', '설명', '삭제'], correctIndex: 2),
Question(question: 'C++에서 클래스를 선언할 때 사용하는 키워드는?', options: ['class', 'def', 'var', 'func'], correctIndex: 0),
Question(question: 'JavaScript에서 배열의 길이는?', options: ['.length', '.size', '.count', '.len'], correctIndex: 0),
Question(question: 'Python에서 오류가 발생할 수 있는 구문은?', options: ['try', 'trap', 'except', 'catch'], correctIndex: 0),
Question(question: 'HTML에서 이미지 삽입 태그는?', options: ['<img>', '<image>', '<src>', '<pic>'], correctIndex: 0),
Question(question: 'React는 어떤 언어 기반인가요?', options: ['Python', 'JavaScript', 'Java', 'C++'], correctIndex: 1),
Question(question: 'Git에서 변경사항을 서버에 반영할 때 사용하는 명령은?', options: ['pull', 'push', 'clone', 'commit'], correctIndex: 1),
Question(question: '소프트웨어 개발 생명주기의 첫 단계는?', options: ['설계', '분석', '테스트', '코딩'], correctIndex: 1),
],
  '한국사': [
Question(question: '고려를 건국한 인물은?', options: ['이성계', '태조 왕건', '세종대왕', '광개토대왕'], correctIndex: 1),
Question(question: '훈민정음 창제 연도는?', options: ['1443년', '1392년', '1450년', '1418년'], correctIndex: 0),
Question(question: '6.25 전쟁은 언제 시작되었나요?', options: ['1945년', '1950년', '1948년', '1953년'], correctIndex: 1),
Question(question: '대한민국 임시정부는 어디서 수립되었나요?', options: ['서울', '도쿄', '상하이', '평양'], correctIndex: 2),
Question(question: '조선의 마지막 왕은?', options: ['순종', '고종', '영조', '정조'], correctIndex: 0),
Question(question: '광개토대왕의 업적은?', options: ['한강 정벌', '신라 통일', '영토 확장', '훈민정음 창제'], correctIndex: 2),
Question(question: '을사늑약이 체결된 해는?', options: ['1904년', '1905년', '1910년', '1919년'], correctIndex: 1),
Question(question: '삼국 통일을 이룬 왕은?', options: ['문무왕', '태종무열왕', '성덕왕', '진덕여왕'], correctIndex: 0),
Question(question: '임진왜란 중 활약한 장수는?', options: ['이순신', '강감찬', '최무선', '정몽주'], correctIndex: 0),
Question(question: '한글 반포는 몇 년?', options: ['1446년', '1443년', '1450년', '1425년'], correctIndex: 0),
Question(question: '조선 시대 중앙 정치 조직은?', options: ['의정부', '삼정승', '비변사', '중추원'], correctIndex: 0),
Question(question: '홍경래의 난이 발생한 지역은?', options: ['함경도', '강원도', '평안도', '경상도'], correctIndex: 2),
Question(question: '갑오개혁이 시작된 해는?', options: ['1894년', '1910년', '1876년', '1905년'], correctIndex: 0),
Question(question: '일제 강점기는 언제 시작되었나?', options: ['1905년', '1910년', '1919년', '1920년'], correctIndex: 1),
Question(question: '국채보상운동은 어떤 성격의 운동인가?', options: ['언론', '경제', '문화', '종교'], correctIndex: 1),
Question(question: '대한제국은 어떤 왕이 선포?', options: ['고종', '순종', '세종', '태조'], correctIndex: 0),
Question(question: '신라의 화백회의는 무엇인가?', options: ['귀족 회의 기구', '군사 조직', '농민 조직', '무역기구'], correctIndex: 0),
Question(question: '독립운동가 안중근이 의거한 장소는?', options: ['하얼빈', '상하이', '서울', '블라디보스토크'], correctIndex: 0),
Question(question: '삼국사기를 지은 사람은?', options: ['김부식', '이이', '신채호', '최치원'], correctIndex: 0),
Question(question: '광복 후 임시정부 주석은?', options: ['김구', '이승만', '박정희', '김일성'], correctIndex: 0),
],
};
List<Question> getQuestionsByCategory(String category) {
  return questionBank[category] ?? [];
}